name: yaz
description: Yaz, State User Options and Content Menager Package For Flutter Client
version: 0.0.4+1
homepage: https://github.com/Mehmetyaz/yaz
repository: https://github.com/Mehmetyaz/yaz

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
